// Boomdle word data.
// ANSWERS: pool of possible solutions (curated, common 5-letter words).
// VALID:   larger set accepted as legal guesses (includes every answer).

const ANSWERS = [
  "blast", "flame", "spark", "burst", "crash", "smoke", "bombs", "blaze",
  "flare", "shell", "torch", "ashes", "ember", "flash", "quake", "storm",
  "power", "surge", "light", "brave", "crane", "slate", "adieu", "audio",
  "house", "mouse", "plant", "grape", "lemon", "table", "chair", "occur",
  "water", "earth", "fluff", "fudge", "glaze", "haunt", "index", "jolly",
  "kayak", "lucky", "money", "noble", "ocean", "pilot", "quiet", "raven",
  "sugar", "tiger", "ultra", "vivid", "wharf", "xenon", "yield", "zebra",
  "amber", "bloom", "cabin", "dwarf", "eagle", "fairy", "giant", "honey",
  "ivory", "joker", "koala", "laser", "magic", "ninja", "olive", "prism",
  "queen", "rocky", "shark", "twist", "unity", "vodka", "witch", "youth",
  "zesty", "alarm", "beach", "candy", "dance", "flint", "spike", "medal",
].filter((w) => w.length === 5);

// Fold answers into the valid set and add a handful of extra legal guesses.
const EXTRA_VALID = [
  "abide", "about", "above", "actor", "acute", "admit", "aloft", "angry",
  "arena", "argue", "aside", "avoid", "await", "badge", "baker", "basic",
  "beast", "began", "begin", "being", "black", "blade", "blame", "blank",
  "blaze", "blend", "blind", "block", "board", "boost", "booth", "bound",
  "brain", "brand", "bread", "break", "brick", "bring", "brush", "buggy",
  "build", "cable", "camel", "canal", "cargo", "carry", "catch", "cause",
  "chase", "cheap", "check", "chess", "chief", "child", "civic", "claim",
  "class", "clean", "clear", "click", "climb", "clock", "close", "cloud",
  "coast", "color", "coral", "count", "court", "cover", "crazy", "cream",
  "crisp", "cross", "crowd", "crown", "curve", "daily", "dairy", "dealt",
  "delta", "depth", "devil", "diary", "dirty", "dizzy", "dodge", "doing",
  "donor", "dough", "dozen", "draft", "drain", "drama", "dream", "dress",
  "drift", "drill", "drink", "drive", "drone", "drove", "drum", "eager",
  "early", "eaten", "elbow", "elder", "elect", "elite", "empty", "enemy",
  "enjoy", "entry", "equal", "error", "essay", "event", "every", "exact",
  "exist", "extra", "fable", "faith", "false", "fancy", "fatal", "fault",
  "favor", "fiber", "field", "fight", "final", "first", "flint", "float",
  "flood", "floor", "flour", "focus", "force", "forge", "forth", "found",
  "frame", "fraud", "fresh", "front", "frost", "fruit", "funny", "genre",
  "ghost", "glass", "globe", "glory", "glove", "grace", "grade", "grain",
  "grand", "grant", "graph", "grass", "great", "greed", "green", "greet",
  "grief", "grill", "grind", "groan", "group", "grown", "guard", "guess",
  "guest", "guide", "habit", "happy", "harsh", "heart", "heavy", "hello",
  "hobby", "honor", "horse", "hotel", "human", "humor", "ideal", "image",
  "issue", "jelly", "jewel", "joint", "judge", "juice", "knife", "knock",
  "known", "label", "labor", "large", "later", "laugh", "layer", "learn",
  "least", "leave", "legal", "level", "lever", "limit", "liver", "lodge",
  "logic", "loose", "lucid", "lunar", "lunch", "lyric", "major", "maker",
  "march", "marsh", "match", "mayor", "meant", "medal", "media", "metal",
  "meter", "might", "minor", "mixer", "model", "moist", "month", "moral",
  "motor", "mount", "mouth", "movie", "music", "naval", "nerve", "never",
  "newly", "night", "noise", "north", "novel", "nurse", "occur", "offer",
  "often", "onion", "opera", "orbit", "order", "organ", "other", "ought",
  "outer", "owner", "paint", "panel", "panic", "paper", "party", "pasta",
  "patch", "pause", "peace", "pearl", "penny", "phase", "phone", "photo",
  "piano", "piece", "plane", "plate", "plaza", "plead", "point", "poker",
  "polar", "porch", "pound", "press", "price", "pride", "print", "prior",
  "prize", "probe", "proof", "proud", "prove", "pulse", "punch", "pupil",
  "quart", "quick", "quilt", "quota", "quote", "radar", "radio", "rally",
  "range", "rapid", "ratio", "reach", "react", "ready", "realm", "rebel",
  "refer", "relax", "relay", "reply", "rider", "ridge", "rifle", "right",
  "rigid", "risky", "rival", "river", "roast", "robot", "rocky", "roman",
  "rough", "round", "route", "royal", "rugby", "ruler", "rural", "salad",
  "sauce", "scale", "scare", "scene", "scope", "score", "scout", "scrap",
  "sense", "serve", "seven", "shade", "shake", "shame", "shape", "share",
  "sharp", "sheep", "sheet", "shelf", "shine", "shiny", "shirt", "shock",
  "shoot", "shore", "short", "shown", "sight", "since", "sixth", "sixty",
  "skate", "skill", "skirt", "skull", "slain", "sleep", "slice", "slide",
  "slope", "small", "smart", "smash", "smell", "smile", "snake", "sneak",
  "solar", "solid", "solve", "sonic", "sorry", "sound", "south", "space",
  "spare", "speak", "speed", "spell", "spend", "spent", "spice", "spike",
  "spine", "spite", "split", "spoke", "sport", "spray", "squad", "stack",
  "staff", "stage", "stain", "stair", "stake", "stall", "stamp", "stand",
  "stare", "start", "state", "steak", "steal", "steam", "steel", "steep",
  "steer", "stern", "stick", "stiff", "still", "sting", "stock", "stone",
  "stood", "stool", "store", "stout", "stove", "strap", "straw", "strip",
  "study", "stuff", "stump", "stunt", "style", "sunny", "super", "surge",
  "swamp", "swarm", "swear", "sweat", "sweet", "swell", "swift", "swing",
  "sword", "syrup", "tasty", "teach", "tempo", "tenth", "thank", "theft",
  "their", "theme", "there", "these", "thick", "thief", "thigh", "thing",
  "think", "third", "those", "three", "threw", "throw", "thumb", "tidal",
  "tight", "title", "toast", "today", "token", "tooth", "topic", "total",
  "touch", "tough", "towel", "tower", "toxic", "trace", "track", "trade",
  "trail", "train", "trait", "trash", "treat", "trend", "trial", "tribe",
  "trick", "tried", "troop", "truck", "truly", "trump", "trunk", "trust",
  "truth", "tulip", "tumor", "tutor", "tweet", "twice", "uncle", "under",
  "union", "upper", "upset", "urban", "usage", "usual", "value", "valve",
  "vapor", "vault", "venue", "verse", "video", "vigor", "villa", "vinyl",
  "viral", "virus", "visit", "vital", "vocal", "voice", "voter", "wagon",
  "waist", "waste", "watch", "weary", "weigh", "weird", "whale", "wheat",
  "wheel", "where", "which", "while", "white", "whole", "whose", "widen",
  "widow", "width", "world", "worry", "worse", "worst", "worth", "would",
  "wound", "wrist", "write", "wrong", "wrote", "yacht", "yeast", "young",
  "zonal",
];

const VALID = new Set([...ANSWERS, ...EXTRA_VALID]);
